import { useState } from 'react';
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom';
import { AnimatePresence, motion } from 'framer-motion';
import { ArrowUpRight, ChevronRight, Menu, X, Check, Play, Sparkles } from 'lucide-react';
import { Toaster, toast } from 'sonner';

const audiences = [
  { id:'golfers', label:'Golfers', title:'More ways to play.', copy:'Find courses, practice, coaches and opportunities around you — without piecing your golf life together across different places.', tone:'sage', href:'/golfers' },
  { id:'coaches', label:'Coaches', title:'More ways to grow.', copy:'Put your expertise in front of golfers who are looking for it. Manage availability, bookings and your professional presence in one place.', tone:'sand', href:'/coaches' },
  { id:'facilities', label:'Facilities', title:'More from what you have.', copy:'Make tee times, practice space, lessons and other inventory easier to discover and book — while building a clearer view of demand.', tone:'forest', href:'/facilities' },
];

function Logo(){return <Link to="/" className="logo" aria-label="ForeSports">FORE<span className="logo-dot"/>SPORTS</Link>}
function Header(){const [open,setOpen]=useState(false); const links=[['Product','/product'],['Golfers','/golfers'],['Coaches','/coaches'],['Facilities','/facilities'],['About','/about']]; return <header className="header"><div className="nav container"><Logo/><nav className={open?'nav-links open':'nav-links'}>{links.map(([label,href])=><NavLink key={href} to={href} onClick={()=>setOpen(false)}>{label}</NavLink>)}</nav><div className="nav-actions"><Link className="button dark small" to="/contact">Get early access <ArrowUpRight size={14}/></Link><button className="icon-button mobile-menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></div></div></header>}
function Footer(){return <footer className="footer"><div className="container footer-grid"><div><Logo/><p>The connective layer for golf in India. Starting in Delhi NCR.</p></div><div><span>Explore</span><Link to="/product">Product</Link><Link to="/golfers">Golfers</Link><Link to="/coaches">Coaches</Link><Link to="/facilities">Facilities</Link></div><div><span>Company</span><Link to="/about">About</Link><Link to="/contact">Contact</Link></div><div><span>Legal</span><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></div></div><div className="container footer-bottom"><span>© 2026 ForeSports Private Limited</span><span>Delhi NCR, India · hello@foresports.in</span></div></footer>}
function Layout(){return <><Header/><main><Routes><Route path="/" element={<Home/>}/><Route path="/product" element={<Product/>}/><Route path="/golfers" element={<AudiencePage type="golfers"/>}/><Route path="/coaches" element={<AudiencePage type="coaches"/>}/><Route path="/facilities" element={<AudiencePage type="facilities"/>}/><Route path="/about" element={<About/>}/><Route path="/contact" element={<Contact/>}/><Route path="/privacy" element={<Legal title="Privacy Policy"/>}/><Route path="/terms" element={<Legal title="Terms of Use"/>}/></Routes></main><Footer/><Toaster position="bottom-center"/></>}
function SectionLabel({children}:{children:React.ReactNode}){return <div className="section-label"><span/> {children}</div>}
function HeroVisual(){return <motion.div className="hero-visual" initial={{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} transition={{duration:.8,ease:[.2,.8,.2,1]}}><div className="hero-grain"/><div className="course-lines"/><div className="hero-brand">FORE <i/> GOLF</div><div className="hero-caption"><span>DELHI NCR</span><b>WHERE THE NETWORK STARTS</b></div><motion.div className="floating-card availability" animate={{y:[0,-8,0]}} transition={{duration:5,repeat:Infinity,ease:'easeInOut'}}><small>TEE TIMES · TODAY</small><strong>Play nearby.</strong><div className="slot"><span>Qutab Golf Course</span><b>8:20</b></div><div className="slot"><span>DLF Golf & Country Club</span><b>11:40</b></div></motion.div><motion.div className="floating-card player" animate={{y:[0,8,0]}} transition={{duration:6,repeat:Infinity,ease:'easeInOut',delay:1}}><div className="avatar">A</div><div><small>COACH</small><strong>Short Game Coach</strong><span>Discover · compare · book</span></div></motion.div><div className="hero-chip"><Sparkles size={13}/> EARLY PRODUCT PREVIEW</div></motion.div>}
function Home(){return <><section className="hero container"><div className="hero-copy"><SectionLabel>The connective layer for golf in India</SectionLabel><h1>Golf, <em>finally</em> connected.</h1><p>Discover where to play. Find the right coach. Book what’s available. Keep your golf life in one place.</p><p className="hero-sub">Fore connects golfers, coaches and facilities through one shared network.</p><div className="button-row"><Link className="button dark" to="/contact">Get early access <ArrowUpRight/></Link><Link className="button light" to="/product">Explore Fore</Link></div><div className="hero-note"><span className="pulse"/> Starting in Delhi NCR · Building with golfers, coaches and facilities</div></div><HeroVisual/></section><Ticker/><Ecosystem/><Problem/><Network/><ProductTeaser/><FinalCTA/></>}
function Ticker(){return <div className="ticker"><div className="ticker-track">DISCOVER <i>•</i> BOOK <i>•</i> LEARN <i>•</i> PLAY MORE <i>•</i> RUN BETTER <i>•</i> DISCOVER <i>•</i> BOOK <i>•</i> LEARN <i>•</i> PLAY MORE <i>•</i> RUN BETTER</div></div>}
function Ecosystem(){return <section className="section container"><div className="section-intro"><div><SectionLabel>One connected network</SectionLabel><h2>Golf has three sides.<br/><span>Fore brings them together.</span></h2></div><p>Golfers need places to play and people to learn from. Coaches need golfers to find them. Facilities need their available time and space to reach the right people.</p></div><div className="ecosystem-list">{audiences.map((a,i)=><motion.article key={a.id} className={`ecosystem-row ${a.tone}`} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.25}} transition={{delay:i*.08,duration:.6}}><div className="ecosystem-art"><span>0{i+1}</span><div className="art-orb"/><div className="art-label">{a.label.toUpperCase()}</div></div><div className="ecosystem-content"><div className="eyebrow-number">0{i+1} / {a.label.toUpperCase()}</div><h3>{a.title}</h3><p>{a.copy}</p><Link to={a.href}>{a.id==='golfers'?'For golfers →':a.id==='coaches'?'For coaches →':'For facilities →'}</Link></div></motion.article>)}</div></section>}
function Problem(){return <section className="problem-section"><div className="container problem-grid"><div><SectionLabel>The way golf works today</SectionLabel><h2>The game is connected.<br/><em>The experience isn’t.</em></h2></div><div className="problem-copy"><p>A golfer might discover a course on one platform, message a coach somewhere else, call to find a tee time and keep the rest of their golf history in their own head.</p><p>Meanwhile, coaches build businesses through referrals and scattered communication. Facilities manage inventory across systems that were never designed to work together.</p><div className="problem-pull">The people, places and opportunities already exist.<br/><strong>They just aren’t connected.</strong></div><Link className="button dark" to="/product">See what Fore connects <ArrowUpRight/></Link></div></div></section>}
function Network(){return <section className="network-section"><div className="container"><SectionLabel>THE NETWORK EFFECT</SectionLabel><h2>One golfer creates a booking.<br/><em>One network creates possibilities.</em></h2><p className="network-intro">When golfers, coaches and facilities share the same network, every interaction can lead to the next one.</p><div className="network-map"><div className="net-line l1"/><div className="net-line l2"/><div className="net-line l3"/><div className="net-node golfer"><b>GOLFERS</b><span>discover · book · play</span></div><div className="net-node coach"><b>COACHES</b><span>teach · grow · build</span></div><div className="net-node facility"><b>FACILITIES</b><span>inventory · demand · operate</span></div><div className="net-core"><strong>FORE</strong><span>one connected golf network</span></div></div><div className="network-caption"><span>A round can lead to a lesson.</span><span>A lesson can lead to another round.</span><span>Available space can become a new customer.</span></div></div></section>}
function ProductTeaser(){return <section className="section container"><div className="product-teaser"><div><SectionLabel>A first look</SectionLabel><h2>Simple on the surface.<br/><span>Powerful underneath.</span></h2><p>Fore should feel simple: find something, choose a time, book it and go play.</p><p>Behind that simplicity is a connected layer for discovery, availability, transactions and golf identity.</p><Link className="text-link" to="/product">Explore the product vision <ArrowUpRight/></Link></div><div className="dashboard"><div className="dash-top"><b>FORE</b><span>MY GOLF</span></div><div className="dash-main"><div className="dash-kicker">YOUR NEXT ROUND</div><h3>Play nearby.</h3><div className="dash-tabs"><span className="active">Courses</span><span>Coaches</span><span>Practice</span></div><div className="dash-item"><div><b>Qutab Golf Course</b><small>18 holes · Delhi</small></div><strong>Book</strong><ChevronRight/></div><div className="dash-item"><div><b>DLF Golf & Country Club</b><small>18 holes · Gurugram</small></div><strong>Explore</strong><ChevronRight/></div></div></div></div></section>}
function FinalCTA(){return <section className="final-cta"><div className="container"><SectionLabel>EARLY ACCESS</SectionLabel><h2>The next round of golf<br/><em>starts with a connection.</em></h2><p>We're starting in Delhi NCR with the golfers, coaches and facilities helping shape Fore from the beginning.</p><div className="button-row center"><Link className="button light" to="/golfers">I'm a golfer</Link><Link className="button light" to="/coaches">I'm a coach</Link><Link className="button acid" to="/facilities">I'm a facility</Link></div></div></section>}
function Product(){return <><PageHero label="Product vision" title={<>One layer connecting<br/><em>the golf ecosystem.</em></>} desc="Fore is being designed as infrastructure for discovery, booking, coaching and golf identity — connecting the supply side with the player side."/><section className="section container"><div className="feature-grid"><Feature num="01" title="Discover" text="Find the right place, person or opportunity without searching across disconnected channels."/><Feature num="02" title="Book" text="Turn real availability into a straightforward booking experience."/><Feature num="03" title="Remember" text="Build a golf profile that becomes more useful with every round, lesson and interaction."/></div></section><Network/><FinalCTA/></>}
function Feature({num,title,text}:{num:string,title:string,text:string}){return <div className="feature-card"><small>{num}</small><h3>{title}</h3><p>{text}</p><ArrowUpRight/></div>}
function AudiencePage({type}:{type:'golfers'|'coaches'|'facilities'}){const a=audiences.find(x=>x.id===type)!; const data={golfers:{label:'For golfers',title:<>Your golf life,<br/><em>in one place.</em></>,desc:'Discover where to play, who to learn from and what fits your game — then keep your golf journey together.',points:[['Discover','Find courses, range time and coaches without jumping between disconnected channels.'],['Book','Choose an available slot and book in a simple, modern flow.'],['Build your game','Keep your golf history, lessons and activity connected to your profile.']]},coaches:{label:'For coaches',title:<>Make your expertise<br/><em>discoverable.</em></>,desc:'A professional home for your coaching business — from profile and availability to bookings and reputation.',points:[['Get discovered','Show your specialties, experience, pricing and availability to golfers actively looking for help.'],['Get booked','Offer trials, individual lessons and packages without the usual coordination overhead.'],['Build reputation','Create a professional presence and a history of reviews that travels with your business.']]},facilities:{label:'For facilities',title:<>Turn availability<br/><em>into opportunity.</em></>,desc:'Put inventory online, reach new demand and build a smarter operating layer around your facility.',points:[['Expose inventory','Put tee times, range bays, lessons and services where golfers can discover them.'],['Increase utilization','Make available inventory visible and bookable instead of relying only on existing channels.'],['Modernize operations','Build toward a single operational layer for inventory, bookings and utilization.']]}}[type]; return <><PageHero label={data.label} title={data.title} desc={data.desc} cta={a.label}/><section className="section container"><div className="section-intro"><div><SectionLabel>Built for you</SectionLabel><h2>The value is different.<br/><span>The network is shared.</span></h2></div></div><div className="feature-grid">{data.points.map((p,i)=><Feature key={p[0]} num={`0${i+1}`} title={p[0]} text={p[1]}/>)}</div></section><JoinForm title={`Join the ${type} early-access list.`}/></>}
function PageHero({label,title,desc,cta}:{label:string,title:React.ReactNode,desc:string,cta?:string}){return <section className="page-hero container"><SectionLabel>{label}</SectionLabel><h1>{title}</h1><p>{desc}</p>{cta&&<Link className="button dark" to="#join">{cta} <ArrowUpRight/></Link>}</section>}
function JoinForm({title}:{title:string}){const submit=(e:React.FormEvent)=>{e.preventDefault();toast.success('Thanks — you’re on the early-access list.');(e.currentTarget as HTMLFormElement).reset()};return <section id="join" className="form-section"><div className="container form-layout"><div><SectionLabel>Get in early</SectionLabel><h2>{title}</h2><p>We're working with a small group of early users and partners as the product takes shape.</p></div><form className="form-card" onSubmit={submit}><div className="form-fields"><label>Name<input required name="name"/></label><label>Email<input required type="email" name="email"/></label><label>City<input required name="city"/></label><label>Phone<input name="phone"/></label></div><button className="button dark" type="submit">Join the waitlist <ArrowUpRight/></button></form></div></section>}
function About(){return <><PageHero label="About ForeSports" title={<>Building the connective<br/><em>layer for golf in India.</em></>} desc="We're building Fore around one simple observation: the golfers, coaches, facilities and opportunities that make golf work already exist. What's missing is a better way for them to find, transact and build relationships with one another."/><section className="section container split-story"><div className="story-image"><span>FORE</span></div><div><SectionLabel>Why Fore</SectionLabel><h2>Golf is growing.<br/><span>The experience is fragmented.</span></h2><p>Golfers navigate disconnected booking channels. Coaches depend heavily on referrals. Facilities manage inventory and demand across systems that were never designed to work together.</p><p>Fore is starting in Delhi NCR and building alongside the people who use the game every day.</p></div></section><FinalCTA/></>}
function Contact(){return <><PageHero label="Contact" title={<>Let's build the<br/><em>next layer of golf.</em></>} desc="For facilities, coaches, investors, partners, press and general enquiries."/><JoinForm title="Tell us what you're building."/></>}
function Legal({title}:{title:string}){return <><PageHero label="Legal" title={title} desc="Information governing use of the ForeSports website."/><section className="section container legal"><h2>Website purpose</h2><p>This website provides information about ForeSports and its planned product. Product descriptions and previews are directional and may change before launch.</p><h2>Contact</h2><p>Questions can be sent to hello@foresports.in.</p></section></>}
export default function App(){const location=useLocation();return <AnimatePresence mode="wait"><motion.div key={location.pathname} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} transition={{duration:.18}}><Layout/></motion.div></AnimatePresence>}
